name: monorepo

include:
    - ./backend/docker-compose.yml
    - ./frontend/docker-compose.yml

services:
    edge:
        image: caddy:2-alpine
        profiles: ['all']
        ports:
            - '80:80'
            - '443:443'
        environment:
            DOMAIN: ${DOMAIN}
            ACME_EMAIL: ${ACME_EMAIL}
        volumes:
            - ./infra/Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - frontend

volumes:
    caddy_data:
    caddy_config:
