import type { ProjectFile } from '@/workers/codeRunner/shared'

export function generateCppProject(): ProjectFile[] {
    return [
        {
            path: 'include/common/types.hpp',
            content: [
                '#pragma once',
                '',
                '#include <string>',
                '#include <vector>',
                '',
                'namespace telemetry {',
                '',
                'struct Sample {',
                '    std::string source;',
                '    int value;',
                '};',
                '',
                'using Samples = std::vector<Sample>;',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/common/math.hpp',
            content: [
                '#pragma once',
                '',
                '#include <vector>',
                '',
                'namespace telemetry {',
                '',
                'template <typename T>',
                'double mean(const std::vector<T>& values) {',
                '    if (values.empty()) return 0.0;',
                '    double sum = 0.0;',
                '    for (const auto value : values) sum += static_cast<double>(value);',
                '    return sum / static_cast<double>(values.size());',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/common/log.hpp',
            content: [
                '#pragma once',
                '',
                '#include <string>',
                '',
                'namespace telemetry {',
                '',
                'std::string line(const std::string& key, const std::string& value);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/io/csv_reader.hpp',
            content: [
                '#pragma once',
                '#include <string>',
                '#include "../common/types.hpp"',
                '',
                'namespace telemetry {',
                '',
                'Samples parse_csv(const std::string& content);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/io/formatter.hpp',
            content: [
                '#pragma once',
                '#include <string>',
                '#include "../alg/stats.hpp"',
                '',
                'namespace telemetry {',
                '',
                'std::string render_stats(const Stats& stats);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/alg/filters.hpp',
            content: [
                '#pragma once',
                '#include "../common/types.hpp"',
                '',
                'namespace telemetry {',
                '',
                'Samples filter_range(const Samples& input, int min_value, int max_value);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/alg/stats.hpp',
            content: [
                '#pragma once',
                '#include "../common/types.hpp"',
                '',
                'namespace telemetry {',
                '',
                'struct Stats {',
                '    int count;',
                '    int min;',
                '    int max;',
                '    double mean;',
                '    int median;',
                '};',
                '',
                'Stats compute_stats(const Samples& input);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'include/app/pipeline.hpp',
            content: [
                '#pragma once',
                '#include <string>',
                '',
                'namespace telemetry {',
                '',
                'std::string run_pipeline(const std::string& csv_content);',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/common/log.cpp',
            content: [
                '#include "../../include/common/log.hpp"',
                '',
                'namespace telemetry {',
                '',
                'std::string line(const std::string& key, const std::string& value) {',
                '    return key + "=" + value + "\\n";',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/io/csv_reader.cpp',
            content: [
                '#include "../../include/io/csv_reader.hpp"',
                '#include <sstream>',
                '',
                'namespace telemetry {',
                '',
                'Samples parse_csv(const std::string& content) {',
                '    Samples out;',
                '    std::istringstream stream(content);',
                '    std::string row;',
                '    while (std::getline(stream, row)) {',
                '        if (row.empty()) continue;',
                "        const auto comma = row.find(',');",
                '        if (comma == std::string::npos) continue;',
                '        const std::string src = row.substr(0, comma);',
                '        const int value = std::stoi(row.substr(comma + 1));',
                '        out.push_back({ src, value });',
                '    }',
                '    return out;',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/alg/filters.cpp',
            content: [
                '#include "../../include/alg/filters.hpp"',
                '',
                'namespace telemetry {',
                '',
                'Samples filter_range(const Samples& input, int min_value, int max_value) {',
                '    Samples out;',
                '    for (const auto& item : input) {',
                '        if (item.value >= min_value && item.value <= max_value) out.push_back(item);',
                '    }',
                '    return out;',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/alg/stats.cpp',
            content: [
                '#include "../../include/alg/stats.hpp"',
                '#include "../../include/common/math.hpp"',
                '#include <algorithm>',
                '',
                'namespace telemetry {',
                '',
                'Stats compute_stats(const Samples& input) {',
                '    if (input.empty()) return { 0, 0, 0, 0.0, 0 };',
                '',
                '    std::vector<int> values;',
                '    values.reserve(input.size());',
                '    for (const auto& sample : input) values.push_back(sample.value);',
                '    std::sort(values.begin(), values.end());',
                '',
                '    const int min = values.front();',
                '    const int max = values.back();',
                '    const int median = values[values.size() / 2];',
                '    return { static_cast<int>(values.size()), min, max, mean(values), median };',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/io/formatter.cpp',
            content: [
                '#include "../../include/io/formatter.hpp"',
                '#include "../../include/common/log.hpp"',
                '#include <sstream>',
                '#include <iomanip>',
                '',
                'namespace telemetry {',
                '',
                'std::string render_stats(const Stats& stats) {',
                '    std::ostringstream out;',
                '    out << line("count", std::to_string(stats.count));',
                '    out << line("min", std::to_string(stats.min));',
                '    out << line("max", std::to_string(stats.max));',
                '    out << line("median", std::to_string(stats.median));',
                '    std::ostringstream mean_text;',
                '    mean_text << std::fixed << std::setprecision(2) << stats.mean;',
                '    out << line("mean", mean_text.str());',
                '    return out.str();',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'src/app/pipeline.cpp',
            content: [
                '#include "../../include/app/pipeline.hpp"',
                '#include "../../include/alg/filters.hpp"',
                '#include "../../include/alg/stats.hpp"',
                '#include "../../include/io/csv_reader.hpp"',
                '#include "../../include/io/formatter.hpp"',
                '',
                'namespace telemetry {',
                '',
                'std::string run_pipeline(const std::string& csv_content) {',
                '    const Samples parsed = parse_csv(csv_content);',
                '    const Samples filtered = filter_range(parsed, 3, 20);',
                '    const Stats stats = compute_stats(filtered);',
                '    return render_stats(stats);',
                '}',
                '',
                '} // namespace telemetry',
                '',
            ].join('\n'),
        },
        {
            path: 'main.cpp',
            content: [
                '#include "include/app/pipeline.hpp"',
                '#include <cstdio>',
                '#include <string>',
                '',
                'int main() {',
                '    const std::string csv =',
                '        "sensor_a,12\\n"',
                '        "sensor_b,8\\n"',
                '        "sensor_a,17\\n"',
                '        "sensor_c,3\\n"',
                '        "sensor_b,30\\n"',
                '        "sensor_a,16\\n";',
                '',
                '    const std::string result = telemetry::run_pipeline(csv);',
                '    std::printf("%s", result.c_str());',
                '    return 0;',
                '}',
                '',
            ].join('\n'),
        },
    ]
}

export const expectedCppOutput = ['count=5', 'min=3', 'max=17', 'median=12', 'mean=11.20', ''].join('\n')

export function generateCProject(): ProjectFile[] {
    return [
        {
            path: 'include/core/types.h',
            content: [
                '#ifndef CORE_TYPES_H',
                '#define CORE_TYPES_H',
                '',
                '#include <stddef.h>',
                '',
                'typedef struct Sample {',
                '    const char* source;',
                '    int value;',
                '} Sample;',
                '',
                'typedef struct SampleBuffer {',
                '    Sample items[32];',
                '    size_t length;',
                '} SampleBuffer;',
                '',
                '#endif',
                '',
            ].join('\n'),
        },
        {
            path: 'include/core/array_utils.h',
            content: [
                '#ifndef CORE_ARRAY_UTILS_H',
                '#define CORE_ARRAY_UTILS_H',
                '',
                '#include <stddef.h>',
                '',
                'static inline double avg_int(const int* values, size_t size) {',
                '    if (size == 0) return 0.0;',
                '    long sum = 0;',
                '    for (size_t i = 0; i < size; i++) sum += values[i];',
                '    return (double)sum / (double)size;',
                '}',
                '',
                '#endif',
                '',
            ].join('\n'),
        },
        {
            path: 'include/io/parse.h',
            content: [
                '#ifndef IO_PARSE_H',
                '#define IO_PARSE_H',
                '',
                '#include "../core/types.h"',
                '',
                'void parse_csv(const char* text, SampleBuffer* out);',
                '',
                '#endif',
                '',
            ].join('\n'),
        },
        {
            path: 'include/alg/histogram.h',
            content: [
                '#ifndef ALG_HISTOGRAM_H',
                '#define ALG_HISTOGRAM_H',
                '',
                '#include "../core/types.h"',
                '',
                'typedef struct Histogram {',
                '    int bins[4];',
                '} Histogram;',
                '',
                'void build_histogram(const SampleBuffer* input, Histogram* out);',
                '',
                '#endif',
                '',
            ].join('\n'),
        },
        {
            path: 'src/io/parse.c',
            content: [
                '#include "../../include/io/parse.h"',
                '#include <stdlib.h>',
                '#include <string.h>',
                '',
                'void parse_csv(const char* text, SampleBuffer* out) {',
                '    out->length = 0;',
                '    const char* row = text;',
                '    while (*row != 0 && out->length < 32) {',
                "        const char* comma = strchr(row, ',');",
                '        if (!comma) break;',
                "        const char* end = strchr(comma + 1, '\\n');",
                '        if (!end) end = comma + strlen(comma);',
                '',
                '        out->items[out->length].source = row;',
                '        out->items[out->length].value = (int)strtol(comma + 1, NULL, 10);',
                '        out->length++;',
                '',
                '        row = (*end == 0) ? end : end + 1;',
                '    }',
                '}',
                '',
            ].join('\n'),
        },
        {
            path: 'src/alg/histogram.c',
            content: [
                '#include "../../include/alg/histogram.h"',
                '',
                'void build_histogram(const SampleBuffer* input, Histogram* out) {',
                '    for (int i = 0; i < 4; i++) out->bins[i] = 0;',
                '    for (size_t i = 0; i < input->length; i++) {',
                '        const int value = input->items[i].value;',
                '        if (value < 5) out->bins[0]++;',
                '        else if (value < 10) out->bins[1]++;',
                '        else if (value < 15) out->bins[2]++;',
                '        else out->bins[3]++;',
                '    }',
                '}',
                '',
            ].join('\n'),
        },
        {
            path: 'src/app/runner.h',
            content: [
                '#ifndef APP_RUNNER_H',
                '#define APP_RUNNER_H',
                '',
                'void run_and_print_report(const char* csv);',
                '',
                '#endif',
                '',
            ].join('\n'),
        },
        {
            path: 'src/app/runner.c',
            content: [
                '#include "runner.h"',
                '#include "../../include/alg/histogram.h"',
                '#include "../../include/core/array_utils.h"',
                '#include "../../include/io/parse.h"',
                '#include <stdio.h>',
                '',
                'void run_and_print_report(const char* csv) {',
                '    SampleBuffer buffer;',
                '    parse_csv(csv, &buffer);',
                '',
                '    Histogram histogram;',
                '    build_histogram(&buffer, &histogram);',
                '',
                '    int values[32];',
                '    for (size_t i = 0; i < buffer.length; i++) values[i] = buffer.items[i].value;',
                '',
                '    printf("bins: %d %d %d %d\\n", histogram.bins[0], histogram.bins[1], histogram.bins[2], histogram.bins[3]);',
                '    printf("avg=%.2f\\n", avg_int(values, buffer.length));',
                '}',
                '',
            ].join('\n'),
        },
        {
            path: 'main.c',
            content: [
                '#include "src/app/runner.h"',
                '',
                'int main(void) {',
                '    const char* csv =',
                '        "n1,2\\n"',
                '        "n2,8\\n"',
                '        "n3,12\\n"',
                '        "n4,17\\n"',
                '        "n5,9\\n"',
                '        "n6,14\\n"',
                '        "n7,3\\n";',
                '    run_and_print_report(csv);',
                '    return 0;',
                '}',
                '',
            ].join('\n'),
        },
    ]
}

export const expectedCOutput = ['bins: 2 2 2 1', 'avg=9.29', ''].join('\n')
